// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221129125905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("EmployerSubstitute", b =>
                {
                    b.Property<int>("EmployersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubstitutesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployersId", "SubstitutesId");

                    b.HasIndex("SubstitutesId");

                    b.ToTable("EmployerSubstitute");
                });

            modelBuilder.Entity("GigSubstitute", b =>
                {
                    b.Property<int>("PositionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubstitutesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PositionsId", "SubstitutesId");

                    b.HasIndex("SubstitutesId");

                    b.ToTable("GigSubstitute");
                });

            modelBuilder.Entity("Persistence.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("Persistence.Models.Gig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("Persistence.Models.Substitute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Substitutes");
                });

            modelBuilder.Entity("EmployerSubstitute", b =>
                {
                    b.HasOne("Persistence.Models.Employer", null)
                        .WithMany()
                        .HasForeignKey("EmployersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Models.Substitute", null)
                        .WithMany()
                        .HasForeignKey("SubstitutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GigSubstitute", b =>
                {
                    b.HasOne("Persistence.Models.Gig", null)
                        .WithMany()
                        .HasForeignKey("PositionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Models.Substitute", null)
                        .WithMany()
                        .HasForeignKey("SubstitutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Models.Gig", b =>
                {
                    b.HasOne("Persistence.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });
#pragma warning restore 612, 618
        }
    }
}
