// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221128094247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Persistence.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Persistence.Models.Gig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubstituteEFCId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("SubstituteEFCId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("Persistence.Models.Substitute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployerEFCId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployerEFCId");

                    b.ToTable("Substitutes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Substitute");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Persistence.Models.EmployerEFC", b =>
                {
                    b.HasBaseType("Persistence.Models.Employer");

                    b.HasDiscriminator().HasValue("EmployerEFC");
                });

            modelBuilder.Entity("Persistence.Models.SubstituteEFC", b =>
                {
                    b.HasBaseType("Persistence.Models.Substitute");

                    b.HasDiscriminator().HasValue("SubstituteEFC");
                });

            modelBuilder.Entity("Persistence.Models.Gig", b =>
                {
                    b.HasOne("Persistence.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Models.SubstituteEFC", null)
                        .WithMany("Positions")
                        .HasForeignKey("SubstituteEFCId");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Persistence.Models.Substitute", b =>
                {
                    b.HasOne("Persistence.Models.EmployerEFC", null)
                        .WithMany("Substitutes")
                        .HasForeignKey("EmployerEFCId");
                });

            modelBuilder.Entity("Persistence.Models.EmployerEFC", b =>
                {
                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("Persistence.Models.SubstituteEFC", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
